[package]
name = "rust-2048"
version = "0.1.0"
authors = ["Andreas Zimmerer <andreas.zimmerer@tum.de>"]

[dependencies]
piston = "*"
piston_window = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
vecmath = "*"
rand = "0.3"
